go_import_path: github.com/minio/minio
#sudo: required

dist: trusty

language: go

os:
- linux
#- osx

#osx_image: xcode7.2

env:
- ARCH=x86_64

branches:
  only:
  - daily

go:
- 1.7.1

addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
      - $GOPATH/bin/minio
    debug: true
